services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: quote-app-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

volumes:
  redis_data:
    driver: local