import React, { useMemo } from 'react';

const QuoteDisclaimer = ({ isVisible }) => {
  const cssClasses = useMemo(() => {
    return `quote-disclaimer ${isVisible ? '' : 'is-hidden'}`;
  }, [isVisible]);

  return (
    <footer data-testid="quote-disclaimer" className={cssClasses}>
      <p>
        Disclaimer: Quotes and authors are generated by an AI for inspirational
        purposes.
      </p>
    </footer>
  );
};

export default QuoteDisclaimer;
