name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint_and_test:
    name: Lint & Test
    runs-on: ubuntu-24.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml build

      - name: Check formatting with Ruff
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm backend ruff format --check .

      - name: Lint with Ruff
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm backend ruff check .

      - name: Run Unit Tests
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm backend pytest -m "not integration"

      - name: Run Integration Tests
        run: |
          docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm \
          -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
          -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          -e AWS_REGION=${{ secrets.AWS_REGION }} \
          backend pytest -m "integration"


  deploy_staging:
    name: Deploy to Staging
    runs-on: ubuntu-24.04

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [lint_and_test]
    steps:
      - name: Deploy to Staging Environment
        run: echo "Deploying to staging..."
