name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build, Lint and Test
    runs-on: ubuntu-24.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml build

      # --- Backend Checks --- #
      - name: Lint with Flake8
        run: docker compose run --rm backend flake8 .

      - name: Check formatting with Black
        run: docker compose run --rm backend black --check .

      - name: Run Backend tests
        run: docker compose run --rm backend pytest

      # --- Frontend Checks --- #
      - name: Lint with ESLint
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm frontend npm run lint

      - name: Check formatting with Prettier
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm frontend npx prettier --check "src/**/*.{js,jsx}" "*.{js,jsx,json}"

      - name: Run Frontend Tests
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm frontend npm test -- --watchAll=false